### ISSUE TITLE
[Feature request] Is there a plan to add a feature for sending audios in addition to images and video?

### ISSUE THREAD

**Issue by alanlzhang** [SebastienBtr/Dash-Chat-2#18]
Voice audio is used quite often in chat, since it's faster and easier to input than typing letters.

**Comment by SebastienBtr** [comment]
Hello, yes this is definitely a feature that will be added! Since you're not the only one interested it should probably be prioritized as the next feature. 
However, I haven't done any research yet to have a better understanding of the complexity

**Comment by SebastienBtr** [comment]
Closing it as it's already mentioned in the readme: `Multiple media support (Audio support: WIP)`
