### ISSUE TITLE
[Question] How to add a custom voice/audio widget?

### ISSUE THREAD

**Issue by Nijinsha** [SebastienBtr/Dash-Chat-2#19]

**Comment by Nijinsha** [comment]
okay. Is this currently on the roadmap?

**Comment by SebastienBtr** [comment]
Yes I'll work on it at the same time as adding a default audio widget

**Comment by Nijinsha** [comment]
any update on this?

**Comment by github-serhat** [comment]
are there any news ?

**Comment by Nijinsha** [comment]
I ended up using my custom widget.
