### ISSUE TITLE
[Feature request/Bug] No way to control padding added when Avatar is disabled

### ISSUE THREAD

**Issue by LegendAF** [SebastienBtr/Dash-Chat-2#46]
**Is your feature request related to a problem? Please describe.**

When `showCurrentUserAvatar` is `false`  in `MessageOptions` you have no way to control the [padding that gets added](https://github.com/molteo-engineering-team/Dash-Chat-2/blob/main/lib/src/widgets/message_row/message_row.dart#L149-L155) (`10`). Our way around was to return a `SizedBox.shrink()` in the `avatarBuilder`. However, it looks like if `showCurrentUserAvatar` is set to `true` it will add a phantom avatar with the same `user.id` (not the other person id in the convo). This means that in our `avatarBuilder` we are not able to hide this avatar which exists in the stack but it set to a `opacity` of `0`.

**Describe the solution you'd like**

A way to control the padding or not add a phantom avatar. Example 3 gets us close to being able to do what we want. But there is a nagging overflow issue because the phantom avatar exists in the stack.

**Example 1 - in avatar builder returning `SizedBox.shrink()` for current user + `showCurrentUserAvatar: false`**
https://user-images.githubusercontent.com/825344/236341244-c0d4eb57-1f4a-45c4-a1ed-0c7ce86cb02b.png

**Example 2 - in avatar builder returning avatar for both +  `showCurrentUserAvatar: true`**
https://user-images.githubusercontent.com/825344/236341213-cc8870a1-ad4a-4638-a769-aaf3aad89e12.png

**Example 3 - in avatar builder returning `SizedBox.shrink()` for current user + `showCurrentUserAvatar: true`**
https://user-images.githubusercontent.com/825344/236341684-4b86eea8-d234-499f-843e-2f3c52d777b5.png

**Comment by LegendAF** [comment]
PR open to address this https://github.com/molteo-engineering-team/Dash-Chat-2/pull/47

**Comment by SebastienBtr** [comment]
Hey, just to be sure that I understand your issue, what you don't want (or would like to custom) is this small 10px padding that I highlighted in red, is that correct?

<img width="384" alt="Screenshot 2023-05-10 at 13 17 17" src="https://github.com/SebastienBtr/Dash-Chat-2/assets/18089010/4933c174-b2e7-4363-ac42-5e30f85cb7d0">

**Comment by LegendAF** [comment]
Yes, that would be ideal. I worked on it in https://github.com/SebastienBtr/Dash-Chat-2/pull/47 but not in love with the naming.
