### ISSUE TITLE
Incompatibility with flutter_localizations because of intl dependency

### ISSUE THREAD

**Issue by Alexxey593** [SebastienBtr/Dash-Chat-2#50]
After Flutter update to 3.10.0 (with Dart 3.0) I can't use dash_chat_2 with flutter_localizations or easy_localisations packages..
Because dash_chat_2 >=0.0.16 depends on intl ^0.18.1 and dash_chat_2 <0.0.16 depends on intl ^0.17.0, every version of dash_chat_2 requires intl ^0.17.0 or ^0.18.1.
And because every version of flutter_localizations from sdk depends on intl 0.18.0, flutter_localizations from sdk is incompatible with dash_chat_2.
So, because eschool_mobile depends on both flutter_localizations from sdk and dash_chat_2 ^0.0.15, version solving failed.

The strange thing is that in pubspec.yaml of dash_chat_2 the "intl: ^0.18.0" is written... Seems like one of the internal dash_chat_2 packages sets additional dependency to  intl ^0.18.1

**Comment by SebastienBtr** [comment]
See https://github.com/SebastienBtr/Dash-Chat-2/pull/49
