### ISSUE TITLE
../lib/src/widgets/input_toolbar/input_toolbar.dart(49,32): error GD65BB2B6: The getter 'View' isn't defined for the class 'InputToolbarState'.

### ISSUE THREAD

**Issue by lucasjinreal** [SebastienBtr/Dash-Chat-2#52]
../lib/src/widgets/input_toolbar/input_toolbar.dart(49,32): error GD65BB2B6: The getter 'View' isn't defined for the class 'InputToolbarState'.

**Comment by SebastienBtr** [comment]
Can you provide more information, what version you're using, and the code to reproduce your issue

**Comment by SebastienBtr** [comment]
I did some research and it's because you didn't upgrade to Flutter 3.10
You can either upgrade your flutter version or use the flutter-3.7 branch that I just created in case you aren't ready to upgrade yet
