### ISSUE TITLE
I am getting an error with DashChat

### ISSUE THREAD

**Issue by kostricanitechnology** [SebastienBtr/Dash-Chat-2#55]
Error: The getter 'View' isn't defined for the class 'InputToolbarState'.
- 'InputToolbarState' is from 'package:dash_chat_2/dash_chat_2.dart'  here is the screen shot https://prnt.sc/kz5d-mnrmQUG

**Comment by SebastienBtr** [comment]
Duplicated of #52

You need to upgrade to Flutter 3.10 or use the flutter-3.7 branch that I created in case you aren't ready to upgrade yet
