### ISSUE TITLE
How to select text/copy messages to clipboard?

### ISSUE THREAD

**Issue by cbmckni** [SebastienBtr/Dash-Chat-2#61]
Hello, I am having issues copying the text from messages to the clipboard. What is the best practice for this? 

I have tried wrapping my DashChat inside a SelectableArea() and also using Clipboard.setData() with no luck. Any advice would be appreciated!

**Comment by SebastienBtr** [comment]
What works for me is the following:

`onLongPressMessage: (ChatMessage message) =>
          Clipboard.setData(ClipboardData(text: message.text))`

**Comment by SebastienBtr** [comment]
I'm closing it, let me know if your need more help

**Comment by prideaux** [comment]
Hi @SebastienBtr 

I am having issues implementing this, where would I place:

```dart
onLongPressMessage: (ChatMessage message) => Clipboard.setData(ClipboardData(text: message.text))
``` 

Also, could I apply this to an icon next to the text of the avatar icon?

Any help would be greatly appreciated.
