### ISSUE TITLE
How to mention user with the same name?

### ISSUE THREAD

**Issue by NguyenBinhasd** [SebastienBtr/Dash-Chat-2#62]
i have a 
`List<Map<String, dynamic>> userList = [{"fullname": "demo", "id": "1"},{"fullname":"demo", "id": "2"}]`
when i mention the first demo user it will take the demo user with id = 1 and mention the demo user it will take the demo user with id= 2
i have tried so many ways to format the String when use onMentionClick function but still fail

**Comment by SebastienBtr** [comment]
Hi, there is no issue with having multiple users with the same name, you can put anything you want in the mention.customProperties, like the user id for instance.

Without any code sample, I cannot tell you what you are doing wrong but if you look closely at the mention.dart example you can see that the user's name doesn't really matter as we save the userId as well in the custom properties.

**Comment by SebastienBtr** [comment]
I'm closing it, let me know if you need more help
