### ISSUE TITLE
Make custom properties nullable in ChatUser.fromJson factory

### ISSUE THREAD

**Issue by Merculiar** [SebastienBtr/Dash-Chat-2#64]
Please, make custom properties nullable in ChatUser.fromJson factory
(customProperties = json['customProperties'] as Map<String, dynamic>?)
<img width="602" alt="Screenshot 2023-07-27 at 13 28 43" src="https://github.com/SebastienBtr/Dash-Chat-2/assets/46864104/f2df373a-9acf-4918-991e-d531a2f2ffa9">

**Comment by Merculiar** [comment]
Same for customProperties fromJson of medias,  quickReplies, mentions and regular customProperties of ChatMessage model;

**Comment by SebastienBtr** [comment]
fixed in version 0.0.18
