### ISSUE TITLE
How to implement message copy on long press

### ISSUE THREAD

**Issue by smartbingari** [SebastienBtr/Dash-Chat-2#81]
I want to add message copy on long press but I don't seem to get it

**Comment by LegendAF** [comment]
Have you tried passing [onLongPressMessage](https://pub.dev/documentation/dash_chat_2/latest/dash_chat_2/MessageOptions/onLongPressMessage.html) to the [messageOptions](https://pub.dev/documentation/dash_chat_2/latest/dash_chat_2/MessageOptions-class.html)?

```
messageOptions: dash_chat.MessageOptions(
  onLongPressMessage:(message) {
    // message.text <-- do something with this
  },
),
```

If so, what kind of issues are you running in to?

**Comment by SebastienBtr** [comment]
Exactly as @LegendAF said, you can use onLongPressMessage or onPressMessage and perform your logic here (showing a bottom sheet with different options for instance). And to perform a clipboard copy you can do something like that:
`await Clipboard.setData(ClipboardData(text: messageText));`
