### ISSUE TITLE
Conflict between cached_video_player and dash_chat_2

### ISSUE THREAD

**Issue by Urminhirpara** [SebastienBtr/Dash-Chat-2#89]
Description:
I encountered a conflict when trying to use both the cached_video_player and dash_chat_2 packages in the same Flutter project. The conflict arises from an error related to the VideoPlayerController when attempting to use the cached_video_player package alongside dash_chat_2.

Error massage:

Running Gradle task 'assembleDebug'...
Building with Flutter multidex support enabled.
../../.pub-cache/hosted/pub.dev/dash_chat_2-0.0.20/lib/src/widgets/message_row/video_player.dart:31:44: Error: Member not found: 'VideoPlayerController.networkUrl'.
    _controller = vp.VideoPlayerController.networkUrl(Uri.parse(widget.url))
                                           ^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/urminhirpara/Development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

**Comment by SebastienBtr** [comment]
Duplicated of https://github.com/SebastienBtr/Dash-Chat-2/issues/82
