### ISSUE TITLE
Error while running Flutter project using package.

### ISSUE THREAD

**Issue by YashrajsinhYz** [SebastienBtr/Dash-Chat-2#90]
I am using dash_chat_2 Version 0.0.19, while running the app it gives below error. Can anyone tell me how to solve it ??

Using Flutter version : 3.3.10

Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
/D:/Flutter%20Sdks/flutter_windows_3.3.10-stable/flutter/.pub-cache/hosted/pub.dartlang.org/dash_chat_2-0.0.19/lib/src/widgets/input_toolbar/input_toolbar.dart:49:32: Error: The getter 'View' isn't defined for the class 'InputToolbarState'.
 - 'InputToolbarState' is from 'package:dash_chat_2/dash_chat_2.dart' ('/D:/Flutter%20Sdks/flutter_windows_3.3.10-stable/flutter/.pub-cache/hosted/pub.dartlang.org/dash_chat_2-0.0.19/lib/dash_chat_2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'View'.
    final double bottomInset = View.of(context).viewInsets.bottom;
                               ^^^^
/D:/Flutter%20Sdks/flutter_windows_3.3.10-stable/flutter/.pub-cache/hosted/pub.dartlang.org/dash_chat_2-0.0.19/lib/src/widgets/input_toolbar/input_toolbar.dart:177:42: Error: A value of type 'OverlayState?' can't be assigned to a variable of type 'OverlayState' because 'OverlayState?' is nullable and 'OverlayState' isn't.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/D:/Flutter%20Sdks/flutter_windows_3.3.10-stable/flutter/packages/flutter/lib/src/widgets/overlay.dart').
    final OverlayState overlay = Overlay.of(context);
                                         ^

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Flutter Sdks\flutter_windows_3.3.10-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Flutter Sdks\flutter_windows_3.3.10-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

**Comment by SebastienBtr** [comment]
Look at the pinned issue: https://github.com/SebastienBtr/Dash-Chat-2/issues/55
