### ISSUE TITLE
Use of arrow key to scroll chats

### ISSUE THREAD

**Issue by KiraKami-dev** [SebastienBtr/Dash-Chat-2#97]
I am creating a web app where in i want to scroll between all the chats using the arrow key

is it possible to do it in dashChat ?? if not it could be an good feature.

**Comment by SebastienBtr** [comment]
Hey, if by scrolling between chats you mean scrolling in the messages list, then I think you should be able to do it since you can pass your own scrollController to MessageListOptions.

Let me know if you have issues implementing it. I'm closing for now

**Comment by KiraKami-dev** [comment]
Hey thanks !
i tried few things but that didn't seem to work.
it would be great if you could provide an example or logic on how i can achieve scroll of allMessages using the up & down arrow key on keyboard.

**Comment by KiraKami-dev** [comment]
Hey @SebastienBtr , scrolling in the messages list works well but i am facing an issue where when i tap on the dashChat widget the focus goes away meaning i can't scroll anymore.
I tried passing around the _focusNode.requestFocus() but it didn't seem to work as well.
It would be great if you could help me with this.

Below is an small code snippet : 

Variable :
```
final ScrollController _scrollController = ScrollController();
  final FocusNode _focusNode = FocusNode();
```

Keyboard listener for arrow keys : 

```
KeyboardListener(
          focusNode: _focusNode,
          autofocus: true,
          onKeyEvent: (event) {
            if (event is KeyDownEvent &&
                event.logicalKey == LogicalKeyboardKey.arrowUp) {
              print("Arrow up pressed");
              _scrollController.animateTo(_scrollController.offset + 100,
                  duration: Duration(milliseconds: 200),
                  curve: Curves.fastEaseInToSlowEaseOut);
            } else if (event is KeyDownEvent &&
                event.logicalKey == LogicalKeyboardKey.arrowDown) {
              print("Arrow down pressed");
              _scrollController.animateTo(_scrollController.offset - 100,
                  duration: Duration(milliseconds: 200),
                  curve: Curves.fastEaseInToSlowEaseOut);
            }
          },
```

Passing scroll to dashChat : 

```
DashChat(
  typingUsers: botTyping,
  currentUser: myself,
  messages: allMessage,
  messageListOptions: MessageListOptions(
    scrollController: _scrollController,
    ),
    )
```
